### ISSUE TITLE
Trying to install/run on HPC using Singularity

### ISSUE THREAD

**Issue by moldach** [bigdatagenomics/cannoli#238]
I'm trying to use this project on an academic HPC.

I'm able to pull the image

```
salloc --time=1:0:0 --mem=1000
module load spark/2.4.4
module load singularity
singularity pull docker://quay.io/biocontainers/cannoli:0.9.0--0
```

However, the command for running is confusing:

```
./bin/cannoli-submit \
    <spark-args>
    -- \
    bwa \
    sample.unaligned.fragments.adam \
    sample.bwa.hg38.alignments.adam \
    sample \
    -index hg38.fa \
    -sequence_dictionary hg38.dict \
    -fragments \
    -use_singularity \
    -image quay.io/ucsc_cgl/bwa:0.7.12--256539928ea162949d8a65ca5c79a72ef557ce7c \
    -add_files
```

There is no `cannoli-submit` folder created when pulling a docker image; it's a `.sif` file....

I believe the `cannoli-submit` folder is created if installing via `conda` and our [HPC admins at ComputeCanada will not let us use `conda`]?(https://docs.computecanada.ca/wiki/Anaconda/en).

The above example looks like it is for a single-end `.fastq` file (called here: `sample`). How should I specify `R1` and `R2` for paired-end alignment?

I appreciate your help

**Comment by heuermh** [comment]
Hello, @moldach!

A bunch of questions here, I'll try to address the last one first.

The above example uses `sample.unaligned.fragments.adam` to refer to a dataset of [`Fragment`](https://javadoc.io/static/org.bdgenomics.bdg-formats/bdg-formats/0.15.0/org/bdgenomics/formats/avro/Fragment.html)s in `.adam` format, which is Apache Parquet written out to disk by [ADAM](https://github.com/bigdatagenomics/adam).  This is the most efficient data format for I/O when using Spark.

`cannoli-submit bwa` also supports interleaved FASTQ (`R1` and `R2` reads interleaved into the same file), so if you have separate read files, you can interleave them via

```bash
$ cannoli-submit interleaveFastq --help
 INPUT1                 : First of pair reads in (possibly compressed) FASTQ
 INPUT2                 : Second of pair reads in (possibly compressed) FASTQ
 OUTPUT                 : Location to write interleaved FASTQ.
```

E.g.
```bash
$ cannoli-submit interleaveFastq \
  sample_R1.fastq \
  sample_R2.fastq \
  sample_interleaved.fastq

$ cannoli-submit bwa \
  sample_interleaved.fastq \
  sample.alignments.adam \
  -sample_id sample \
  ...
```

If you wanted to write the alignments out as BAM format rather than [`Alignment`](https://javadoc.io/static/org.bdgenomics.bdg-formats/bdg-formats/0.15.0/org/bdgenomics/formats/avro/Alignment.html)s in Apache Parquet format, use

```bash
$ cannoli-submit bwa \
  sample_interleaved.fastq \
  sample.bam \
  -sample_id sample \
  -single \
  ...
```

Hope that helps.

As far as the other questions, running Spark on HPC is rather environment specific.  Do you know how to run a normal Spark job on your cluster, with some job requirements (e.g. Spark options `--executor-memory 48G --executor-cores 32 ...`)?

I might then be able to help you figure out how to run ADAM and Cannoli jobs (which both use Spark).

**Comment by heuermh** [comment]
Hello @moldach, any progress on this issue?  I am available to help further if necessary.

**Comment by moldach** [comment]
Hi @heuermh I appreciate your response thank you. Sorry, it's just that this has been side-lined for the moment. When I get a chance to revisit this I will let you know. Thanks again

**Comment by heuermh** [comment]
Thanks for letting me know!  I'll keep this issue open, please check back in when you get the chance.

**Comment by heuermh** [comment]
Closing for now, please reopen if necessary!
